# Figure Grolle
input <- pheno.treat
xxlim <- range(input$control, na.rm=TRUE)
yylim <- range(cbind(input$"TT2", input$"TT3", input$"TT4"), na.rm=TRUE)
pdf ("Fig.Grolle.pdf", width=13, height=6.5, pointsize=8)
par(mfrow=c(1,3), mar=c(1,1,1.5,0.5), mgp=c(1,1,0), oma=c(3,3,1,0.5), cex=3)
plot(input$control, input$TT2, main="varmere", xlim=xxlim, ylim=yylim, axes=FALSE, pch=16, ylab="", xlab="", col="darkblue")
box(); axis(1, labels=TRUE); axis(2, labels=TRUE)
bars(input$control, input$TT2, input$control.sd, c="grey")
bars.y(input$control, input$TT2, input$tt2.sd, c="grey")
abline(1,1, lty=2)
par(new=TRUE)
plot(input$control, input$TT2, main="varmere", xlim=xxlim, ylim=yylim, axes=FALSE, pch=16, ylab="", xlab="", col="darkblue")
text(1,13.7,"a)")
#legend(1.2,14, legend=c("våt", "intermediær", "tørr"), col=c("darkblue", "blue", "lightblue"), pch=16, cex=0.8, bty = "n")
plot(input$control, input$TT3, main="våtere", xlim=xxlim, ylim=yylim, axes=FALSE, pch=16, ylab="", xlab="", col="darkblue")
box(); axis(1, labels=TRUE); axis(2, labels=FALSE)
bars(input$control, input$TT3, input$control.sd, c="grey")
bars.y(input$control, input$TT3, input$tt3.sd, c="grey")
abline(1,1, lty=2)
par(new=TRUE)
plot(input$control, input$TT3, main="våtere", xlim=xxlim, ylim=yylim, axes=FALSE, pch=16, ylab="", xlab="", col="darkblue")
text(1,13.7,"b)")
#legend(1.2,14, legend=c("alpin", "intermediær"), col=c("darkblue"), pch=c(17,16), cex=0.8, bty = "n")
plot(input$control, input$TT4, main="varmere & våtere", xlim=xxlim, ylim=yylim, axes=FALSE, pch=16, ylab="", xlab="", col="darkblue")
box(); axis(1, labels=TRUE); axis(2, labels=FALSE)
bars(input$control, input$TT4, input$control.sd, c="grey")
bars.y(input$control, input$TT4, input$tt4.sd, c="grey")
abline(1,1, lty=2)
par(new=TRUE)
plot(input$control, input$TT4, main="varmere & våtere", xlim=xxlim, ylim=yylim, axes=FALSE, pch=16, ylab="", xlab="", col="darkblue")
text(1,13.7,"c)")
mtext("Kontroll", 1, outer=TRUE, line=1.3, cex=3)
mtext("Transplant", 2, outer=TRUE, line=1.3, cex=3)
dev.off()